server:
  port: 8085
  context-path: /computer
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zzu
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: system
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.zzh.entity
  mapper-locations: classpath:com/zzh/dao/*.xml
